---
kind: pipeline
name: build
type: kubernetes

node_selector:
  kubernetes.io/arch: arm64

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: registry.lan/krichy/rrdcached
    registry: registry.lan
    insecure: true
    auto_tag: true

  privileged: true
  volumes:
  - name: docker
    path: /var/lib/docker

volumes:
- name: docker
  temp: {}
