---
kind: pipeline
name: build
type: kubernetes

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: ghcr.io/kubernetize/rrdcached
    registry: ghcr.io
    auto_tag: true
    auto_label: false
    username: rkojedzinszky
    password:
      from_secret: ghcr.io.password
    mirror:
      from_secret: hub_docker_mirror

  privileged: true
  volumes:
  - name: docker
    path: /var/lib/docker

volumes:
- name: docker
  temp: {}
